#!/usr/bin/env python3
import os
import glob as glob
import sys

os.system('mkdir -p ./dumpMC/log/')
os.system('mkdir -p ./dumpMC/err/')
os.system('mkdir -p ./dumpMC/out/')
os.system('g++ `root-config --glibs --cflags` -lEG -I TPCNtupleFormat/ `$FASTJETDIR/bin/fastjet-config --cxxflags --libs --plugins` -o bin/convertMC.exe convertMC.C')

PDLINPUT_txt = '''
*
* PDLINPUT file for DES multievt request
*
FILE = {}
*
'''

#tin = '/eos/opendata/delphi/simulated-data/cern/qqps/v94c/91.25/qqps*.sdst'
#tin = '/eos/opendata/delphi/simulated-data/cern/qqps/v94c/91.25/qqps_91.25_21000.sdst'
#tout = '/eos/user/z/zhangj/DELPHI/simulation/1994_v2/qqps/'

#tin = '/eos/opendata/delphi/simulated-data/karlsruhe/wwex_postdst/v98d2/189/*5798*.xsdst'
#tout = '/eos/user/z/zhangj/DELPHI/simulation/1998/wwex_postdst/v98d2/189/'

#tin = '/eos/opendata/delphi/collision-data/Y13737/*.al'
#tout = '/eos/user/z/zhangj/DELPHI/simulation/1998_v2/v98d2/wwpy/'

#tin = '/eos/opendata/delphi/collision-data/Y01461/*.al'
#tin = '/eos/opendata/delphi/collision-data/Y01461/Y01461.9.al'
#tout = '/eos/user/z/zhangj/DELPHI/simulation/1998_v2/v98d2/zgpy/'

#files = glob.glob(tin)


#tin = '/eos/opendata/delphi/collision-data/Y13745/Y13745.{105..112}.al'
#tout = '/eos/user/z/zhangj/DELPHI/simulation/1998_v2/v98d2/eegg/'
#files = [
#    f
#    for i in range(105, 113)
#    for f in glob.glob(f"/eos/opendata/delphi/collision-data/Y13745/Y13745.{i}.al")
#]
#print(files)

#tout = '/eos/user/z/zhangj/DELPHI/simulation/1998_v2/v98d2/kora/'
#files = [
#    f
#    for i in range(83, 88)
#    for f in glob.glob(f"/eos/opendata/delphi/collision-data/Y13741/Y13741.{i}.al")
#]
#print(files)

#tin = '/eos/opendata/delphi/simulated-data/lyon/kk2f4144/v98e/188.6/*xsdst'
#tout = '/eos/user/z/zhangj/DELPHI/simulation/1998_v2/v98e1/kk2f4144_qqar/'
#files = glob.glob(tin)

#tin = '/eos/opendata/delphi/simulated-data/lyon/kk2f4143/v98e/188.6/kk2f4143_qq_188.6_2*xsdst'
#tout = '/eos/user/z/zhangj/DELPHI/simulation/1998_v2/v98e1/kk2f4143_qq/'
#files = glob.glob(tin)

tin = '/eos/opendata/delphi/simulated-data/ral/kk2f4144/v98e/188.6/*xsdst'
tout = '/eos/user/z/zhangj/DELPHI/simulation/1998_v2/v98e1/kk2f4144_ttsp/'
files = glob.glob(tin)

#tin = '/eos/opendata/delphi/simulated-data/cern/wphact24/v98e/188.6/wphact24_4q_188.6_80.4_2054*xsdst'
#tout = '/eos/user/z/zhangj/DELPHI/simulation/1998_v2/v98e1/wphact24_4q/'
#files = glob.glob(tin)

#tin = '/eos/opendata/delphi/simulated-data/cern/wphact24/v98e/188.6/wphact24_cc_188.6_80.4_*.xsdst'
#tout = '/eos/user/z/zhangj/DELPHI/simulation/1998_v2/v98e1/wphact24_cc/'
#files = glob.glob(tin)

#tin = '/eos/opendata/delphi/simulated-data/cern/wphact21/v98e/188.6/wphact21_nc4f_188.6_80.4_21*'
#tout = '/eos/user/z/zhangj/DELPHI/simulation/1998_v2/v98e1/wphact21_nc/'
#files = glob.glob(tin)

#tin = '/eos/opendata/delphi/simulated-data/ral/qedbk23/eegg/v98e/188.0/EK577*'
#tout = '/eos/user/z/zhangj/DELPHI/simulation/1998_v2/v98e1/qedbk23eegg/'
#files = glob.glob(tin)

os.system(f'mkdir -p {tout}')

if len(sys.argv) > 1:
    if len(sys.argv) == 3:
        tin = sys.argv[1]
        tout = sys.argv[2]
    else:
        print(sys.argv)
        print("Please specify input and output!")
        sys.exit()

os.chdir('dumpMC')

for al in files:
    f = open('PDLINPUT', 'w')
    f.write(PDLINPUT_txt.format(al))
    f.close()
    basename=os.path.basename(al.strip('.al'))
    os.system('cat PDLINPUT')
    os.system(f'bash dump.sh {basename}')
    os.system('ls -lh')
    os.system(f'echo Recorded `grep -c HAPPY dump.{basename}.log` events!')
    os.system(f'mv dump.{basename}.log log/')
    os.system(f'mv dump.{basename}.err err/')
    os.system(f'../bin/convertMC.exe log/dump.{basename}.log out/{basename}.root')
    os.system(f'mv out/{basename}.root {tout}')
    os.system(f'rm log/dump.{basename}.log')
    os.system(f'rm err/dump.{basename}.err')
